#!/bin/bash
# Matt Day's custom .bash_profile file
# Not sure where I got all this from, it showed up along the way!
# Latest copy always here: https://github.com/mattsday/dotfiles/

# Set up environment variables

# Load any local config first
if [[ -f "${HOME}/.bash_profile_config" ]]; then
    . "${HOME}/.bash_profile_config"
fi

# Load the full shebang
if [[ -f "${HOME}/.bashrc" ]]; then
    . "${HOME}/.bashrc"
fi

# ======================
# Plug-ins and Resources
# ======================
# Check for (and source) additional plugins and resources, such as local config
# files
if [[ -f "${HOME}/.bash_profile_local" ]]; then
    . "${HOME}/.bash_profile_local"
fi
