#!/bin/bash
# This file loads the Cisco proxy settings.
# Latest copy always here: https://github.com/mattsday/dotfiles/

# Use same proxy host for all protocols
export proxy=http://proxy.esl.cisco.com:80/
export http_proxy=$proxy
export https_proxy=$proxy
export ftp_proxy=$proxy
export PROXY=$proxy
export HTTP_PROXY=$proxy
export HTTPS_PROXY=$proxy
export FTP_PROXY=$proxy

# Whitelist common lab ranges 
CORP_1_WHITELIST="$(echo 10.52.208.{0..255} | sed 's/ /,/g')"
CORP_2_WHITELIST="$(echo 10.51.8.{0..255} | sed 's/ /,/g')"

# Frontend/App/Backend whitelists
FE_WHITELIST="$(echo 192.168.210.{0..255} | sed 's/ /,/g')"
APP_WHITELIST="$(echo 192.168.211.{0..255} | sed 's/ /,/g')"
BE_WHITELIST="$(echo 192.168.212.{0..255} | sed 's/ /,/g')"
no_proxy=".cisco.com,127.0.0.1,localhost,local.home,0.0.0.0,"
no_proxy+="$CORP_1_WHITELIST,$CORP_2_WHITELIST"
no_proxy+="$FE_WHITELIST,$APP_WHITELIST,$BE_WHITELIST"
export no_proxy
export NO_PROXY=$no_proxy

# vim: syntax=zsh
