#!/bin/sh
# This file loads the Cisco proxy settings.
# Latest copy always here: https://github.com/mattsday/dotfiles/

# Use same proxy host for all protocols
export proxy=http://proxy.esl.cisco.com:80/
export http_proxy=$proxy
export https_proxy=$proxy
export ftp_proxy=$proxy
export PROXY=$proxy
export HTTP_PROXY=$proxy
export HTTPS_PROXY=$proxy
export FTP_PROXY=$proxy

# Whitelist common lab ranges
CORP_A_WHITELIST=`seq -f "10.52.208.%g" -s "," 0 255 | sed 's/.$//'`
CORP_B_WHITELIST=`seq -f "10.51.8.%g" -s "," 0 255 | sed 's/.$//'`

# Frontend/App/Backend whitelists
FE_WHITELIST=`seq -f "192.168.210.%g" -s "," 0 255 | sed 's/.$//'`
APP_WHITELIST=`seq -f "192.168.211.%g" -s "," 0 255 | sed 's/.$//'`
BE_WHITELIST=`seq -f "192.168.212.%g" -s "," 0 255 | sed 's/.$//'`

# Common OpenStack subnet whitelist
OS_WHITELIST=`seq -f "10.0.0.%g" -s "," 0 255 | sed 's/.$//'`

export no_proxy=".cisco.com,127.0.0.1,localhost,local.home,0.0.0.0,$CORP_A_WHITELIST,$CORP_B_WHITELIST,$FE_WHITELIST,$APP_WHITELIST,$BE_WHITELIST,$OS_WHITELIST"
export NO_PROXY=$no_proxy

# vim: syntax=sh
