#!/bin/sh
# This file loads various defaults on virtually any bourne-compatible
# shell. It's designed to be POSIX and flavour-neutral. Any rc file
# can load this (e.g. zshrc, kshrc, bashrc) for consistency across
# environments
#
# Latest copy always here: https://github.com/mattsday/dotfiles/
#
# shellcheck disable=SC1090

# Execute any local bourne script config - local config should go in _local below:
if [ -f "$HOME/.shell_common_config" ]; then
	. "$HOME/.shell_common_config"
fi

# Set some local utilities as default (this must be top of this file after local config)
if [ -d /usr/local/bin ]; then
	PATH=/usr/local/bin:$PATH
	export PATH
fi
if [ -d /usr/local/sbin ]; then
	PATH=/usr/local/sbin:$PATH
	export PATH
fi
if [ -d /snap/bin ]; then
	PATH=$PATH:/snap/bin
fi

# =================
# Alias definitions
# =================
# Update the alias file
if [ -f "$HOME/.update_aliases" ]; then
	sh "$HOME/.update_aliases"
fi

# Load aliases from a separate file and parse them in to bourne-compatible notation
if [ -f "$HOME/.aliases" ]; then
	. "$HOME/.aliases"
fi

# Check if sdkman is installed
if [ -f "$HOME/.sdkman/bin/sdkman-init.sh" ]; then
	. "$HOME/.sdkman/bin/sdkman-init.sh"
fi

# Find function to quickly look for things in pwd
f() {
	find . -iname "*$1*"
}

# Grep find
gf() {
	grep -Ri "$1"
}

# Disable shell history for session
disable_hist() {
	unset HISTFILE
	#shellcheck disable=SC2039
	set +o history 2>/dev/null
}

extract() {
	extr "$@"
}

# Extract archives
extr() {
	for file in "$@"; do
		if [ -f "$file" ]; then
			case $file in
			*.tar.bz2) tar xvjf "$@" && rm "$@" ;;
			*.tar.gz) tar xvzf "$@" && rm "$@" ;;
			*.xz) tar xvJf "$@" && rm "$@" ;;
			*.bz2) bunzip2 "$@" && rm "$@" ;;
			*.rar) unrar x "$@" && rm "$@" ;;
			*.gz) gunzip "$@" && rm "$@" ;;
			*.tar) tar xvf "$@" && rm "$@" ;;
			*.tbz2) tar xvjf "$@" && rm "$@" ;;
			*.tgz) tar xvzf "$@" && rm "$@" ;;
			*.zip) unzip "$@" && rm "$@" ;;
			*.Z) uncompress "$@" && rm "$@" ;;
			*.7z) 7za x "$@" && rm "$@" ;;
			*) echo "don't know how to extract '$*'..." ;;
			esac
		fi
	done
}

# =====================
# Environment variables
# =====================
# These affect most systems and are (usually) harmless if run without...

# Check if proxy settings have been created
if [ -f "$HOME/.sh_proxy_settings" ]; then
	. "$HOME/.sh_proxy_settings"
fi

# =====================
# Colour support
# =====================
# Checks about terminal colour support

# By default disable colour for root (enable by creating ~/.enable_shell_colour):
if [ "$(id -u)" = 0 ]; then
	colours=7
fi

# Check if colours are forced-enabled/disabled:
if [ -f "$HOME/.enable_shell_colour" ]; then
	colours=256
elif [ -f "$HOME/.disable_shell_colour" ]; then
	colours=7
elif [ -z $colours ]; then
	# Test for number of colours
	if ! colours=$(tput colors 2>/dev/null); then
		# If tput errors out then try and fix...
		# If it's reporting as a 256-colour term try changing to just an xterm
		[ "$TERM" = "xterm-256color" ] && TERM=xterm && export TERM
		if ! colours=$(tput colors 2>/dev/null); then
			# If that still fails then disable colour
			colours=7
		fi
	fi
fi

# Disable software flow control (XON/OFF) / AKA: why did ctrl-s pause my term?
if command -v stty >/dev/null 2>&1; then
	stty -ixon
fi

# Execute any local bourne scripts:
if [ -f "$HOME/.shell_common_local" ]; then
	. "$HOME/.shell_common_local"
fi

# vim: syntax=sh
