terminal:
  colorScheme:
    name: Breeze Dark
    foreground: '#fcfcfc'
    background: '#232627'
    cursor: '#bbbbbb'
    colors:
      - '#232627'
      - '#ed1515'
      - '#11d116'
      - '#f67400'
      - '#1d99f3'
      - '#9b59b6'
      - '#1abc9c'
      - '#fcfcfc'
      - '#000000'
      - '#c0392b'
      - '#1cdc9a'
      - '#fdbc4b'
      - '#3daee9'
      - '#8e44ad'
      - '#16a085'
      - '#ffffff'
  font: JetBrains Mono
  frontend: xterm-webgl
  environment: {}
  profile: zsh
  alwaysUseWorkingDirectory: true
  autoOpen: true
  fontSize: 13
  ligatures: true
  background: colorScheme
  cursorBlink: false
  customColorSchemes:
    - name: Breeze Dark
      foreground: '#fcfcfc'
      background: '#232627'
      cursor: '#bbbbbb'
      colors:
        - '#232627'
        - '#ed1515'
        - '#11d116'
        - '#f67400'
        - '#1d99f3'
        - '#9b59b6'
        - '#1abc9c'
        - '#fcfcfc'
        - '#000000'
        - '#c0392b'
        - '#1cdc9a'
        - '#fdbc4b'
        - '#3daee9'
        - '#8e44ad'
        - '#16a085'
        - '#ffffff'
hotkeys:
  profile: {}
  paste:
    - - Ctrl-Shift-V
    - - Ctrl-V
  shell: {}
  settings:
    - - 'Ctrl-Shift-,'
  zoom-out:
    - - Ctrl--
    - - Ctrl-Shift--
    - - Ctrl-NumpadSubtract
  zoom-in:
    - - Ctrl-=
    - - Ctrl-Shift-=
    - - Ctrl-NumpadAdd
  reset-zoom:
    - - Ctrl-0
    - - Ctrl-Numpad0
  next-tab:
    - - Ctrl-Shift-Right
    - - Ctrl-Tab
    - - Ctrl-PageUp
  previous-tab:
    - - Ctrl-Shift-Left
    - - Ctrl-Shift-Tab
    - - Ctrl-PageDown
serial: {}
ssh: {}
appearance:
  theme: Standard
  frame: native
enableAnalytics: false
enableWelcomeTab: false
pluginBlacklist:
  - ssh
