#!/bin/sh
week=604800
# Get the date
date=`date +%s 2>/dev/null | xargs`
if [ "$date" = "%s" ]; then
	# Horrible Solaris workaround
	date=`truss /usr/bin/date 2>&1 | grep ^time | awk -F= '{print $2}' | xargs`
fi

# If no argument is passed then check the last-updated time
if [ -z $1 ]; then
	lastdate=`cat "$HOME/.alias_update_time"`
	diff=`expr $date - $lastdate`
	if [ $week -gt $diff ]; then
		exit
	fi
fi

SH_ALIAS_FILE="$HOME/.aliases"
CSH_ALIAS_FILE="$HOME/.csh_aliases"

rm $SH_ALIAS_FILE >/dev/null 2>&1
rm $CSH_ALIAS_FILE >/dev/null 2>&1

FILE_COMMENT="# This file is auto generated and replaced every 7 days.
\n# Edit '$HOME/.alias_list' to change them and then run
\n# \`$HOME/.update_aliases force\` to update this file."

echo $FILE_COMMENT > $SH_ALIAS_FILE
echo $FILE_COMMENT > $CSH_ALIAS_FILE

add_alias() {
	IFS='@'
	for alias in $1; do
		alias_name=`echo $alias | awk -F= '{print $1}' | xargs`
		alias_data=`echo $alias | awk -F= '{print $2}'`
		# Check if the command needs to be expanded
		echo $alias_data | egrep '^!.*' >/dev/null 2>&1
		if [ $? = 0 ]; then
			ocmd=`echo $alias_data | awk '{ print $1 }' | sed 's/^!//'`
			wcmd=`which $ocmd 2>/dev/null`
			if [ $? = 0 ]; then
				alias_data="`echo $wcmd $alias_data | sed 's|!'$ocmd'||' | xargs`"
			fi
			unset wcmd ocmd
		fi
		echo alias $alias_name=\'$alias_data\' >> $SH_ALIAS_FILE
		echo alias $alias_name \'$alias_data\' >> $CSH_ALIAS_FILE
	done
}

add_export() {
	IFS='@'
	for export in $1; do
		export_name=`echo $export | awk -F= '{print $1}' | xargs`
		export_data=`echo $export | awk -F= '{print $2}' | xargs`
		# Check if the command needs to be expanded
		echo $export_data | egrep '^!.*' >/dev/null 2>&1
		if [ $? = 0 ]; then
			ocmd=`echo $export_data | awk '{ print $1 }' | sed 's/^!//'`
			wcmd=`which $ocmd 2>/dev/null`
			if [ $? = 0 ]; then
				export_data="`echo $wcmd $export_data | sed 's|!'$ocmd'||' | xargs`"
			fi
			unset wcmd ocmd
		fi
		echo $export_name=\'$export_data\' >> $SH_ALIAS_FILE
		echo export $export_name >> $SH_ALIAS_FILE
		echo setenv $export_name \'$export_data\' >> $CSH_ALIAS_FILE
	done
}

while IFS='' read -r line || [ -n "$line" ]; do
	case $line in
		# Ignore comments
		'#'*)
			;;
		# Check for executables
		'alias @'*|'export @'*)
			# Get the list of command_list to test
			command_list=`echo $line | awk '{print $2}' | sed 's/^@//'`
			IFS=,
			execute=1
			for command in $command_list; do
				case $command in
					# If it's an absolute path just test if it is executable
					*\/*)
						if [ ! -x "$command" ]; then
							execute=0
							break
						fi
						;;
					# Otherwise search the path for it
					*)
						if ! command -v $command >/dev/null 2>&1; then
							execute=0
							break
						fi
				esac
			done
			IFS=''
			if [ $execute = 1 ]; then
				type=`echo $line | awk '{ print $1 }' | xargs`
				if [ "$type" = alias ]; then
					add_alias `echo $line | awk '{ print $0 }' | sed 's/^alias//' | sed 's|@'"$command_list"'||' | xargs`
				elif [ "$type" = export ]; then
					add_export `echo $line | awk '{ print $0 }' | sed 's/^export//' | sed 's|@'"$command_list"'||' | xargs`
				fi
			fi
			;;
		export*)
				add_export `echo $line | sed 's/^export//' | xargs`
			;;
		alias*)
			if [ ! -z "$line" ]; then
				add_alias `echo $line | sed 's/^alias//' | xargs`
			fi
			;;
	esac
done < "$HOME/.alias_list"

# Write out last update time:
echo $date>"$HOME/.alias_update_time"

# vim: syntax=sh
